
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FENRIR
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    Viaje viaje;
    
    
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        viaje = new Viaje();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        ButtonLimpiar1 = new javax.swing.JButton();
        DialogoViaje = new javax.swing.JDialog();
        EtiquetaDestino = new javax.swing.JLabel();
        EtiquetaHotel = new javax.swing.JLabel();
        ButtonCanarias = new javax.swing.JRadioButton();
        ButtonPortugal = new javax.swing.JRadioButton();
        ButtonValencia = new javax.swing.JRadioButton();
        Button3Estrellas = new javax.swing.JRadioButton();
        Button4Estrellas = new javax.swing.JRadioButton();
        Button5Estrellas = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        SpinnerNoches = new javax.swing.JSpinner();
        ButtonSalir2 = new javax.swing.JButton();
        ButtonAceptar2 = new javax.swing.JButton();
        ButtonLimpiar2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        buttonGroupDestino = new javax.swing.ButtonGroup();
        buttonGroupHotel = new javax.swing.ButtonGroup();
        EtiquetaNombreYApellidos = new javax.swing.JLabel();
        CTextoNombreApellidos = new javax.swing.JTextField();
        EtiquetaCiudad = new javax.swing.JLabel();
        ComboBoxCiudades = new javax.swing.JComboBox<>();
        EtiquetaSexo = new javax.swing.JLabel();
        EtiquetaFechNacimiento = new javax.swing.JLabel();
        LContraseña = new javax.swing.JLabel();
        LRContraseña = new javax.swing.JLabel();
        ButtonHombre = new javax.swing.JRadioButton();
        ButtonMujer = new javax.swing.JRadioButton();
        SpinnerFechNacimiento = new javax.swing.JSpinner();
        ComboBoxMeses = new javax.swing.JComboBox<>();
        passWord = new javax.swing.JPasswordField();
        rePassword = new javax.swing.JPasswordField();
        CheckBoxCOndicionesDeUso = new javax.swing.JCheckBox();
        ButtonLimpiar = new javax.swing.JButton();
        ButtonAceptar = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_Archivo = new javax.swing.JMenu();
        Menu_Edita = new javax.swing.JMenu();

        ButtonLimpiar1.setText("Limpiar");

        DialogoViaje.setBackground(new java.awt.Color(30, 129, 229));
        DialogoViaje.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        DialogoViaje.setSize(new java.awt.Dimension(400, 600));

        EtiquetaDestino.setText("DESTINO");

        EtiquetaHotel.setText("HOTEL");

        buttonGroupDestino.add(ButtonCanarias);
        ButtonCanarias.setText("Canarias");

        buttonGroupDestino.add(ButtonPortugal);
        ButtonPortugal.setText("Portugal");

        buttonGroupDestino.add(ButtonValencia);
        ButtonValencia.setText("Valencia");

        buttonGroupHotel.add(Button3Estrellas);
        Button3Estrellas.setText("3 estrellas - 50€");

        buttonGroupHotel.add(Button4Estrellas);
        Button4Estrellas.setText("4 estrellas - 75€");

        buttonGroupHotel.add(Button5Estrellas);
        Button5Estrellas.setText("5 estrellas - 100€");

        jLabel1.setText("NOCHES");

        ButtonSalir2.setText("Salir");
        ButtonSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalir2ActionPerformed(evt);
            }
        });

        ButtonAceptar2.setText("Aceptar");
        ButtonAceptar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAceptar2ActionPerformed(evt);
            }
        });

        ButtonLimpiar2.setText("Limpiar");

        TextArea1.setColumns(20);
        TextArea1.setRows(5);
        jScrollPane1.setViewportView(TextArea1);

        javax.swing.GroupLayout DialogoViajeLayout = new javax.swing.GroupLayout(DialogoViaje.getContentPane());
        DialogoViaje.getContentPane().setLayout(DialogoViajeLayout);
        DialogoViajeLayout.setHorizontalGroup(
            DialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogoViajeLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(ButtonLimpiar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonAceptar2)
                .addGap(59, 59, 59)
                .addComponent(ButtonSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(DialogoViajeLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(DialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DialogoViajeLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(EtiquetaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(EtiquetaHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DialogoViajeLayout.createSequentialGroup()
                        .addGroup(DialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonCanarias)
                            .addComponent(ButtonPortugal)
                            .addComponent(ButtonValencia))
                        .addGap(110, 110, 110)
                        .addGroup(DialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button5Estrellas)
                            .addComponent(Button4Estrellas)
                            .addComponent(Button3Estrellas, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DialogoViajeLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SpinnerNoches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        DialogoViajeLayout.setVerticalGroup(
            DialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogoViajeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(DialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtiquetaHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCanarias)
                    .addComponent(Button3Estrellas))
                .addGap(18, 18, 18)
                .addGroup(DialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonPortugal)
                    .addComponent(Button4Estrellas))
                .addGap(18, 18, 18)
                .addGroup(DialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonValencia)
                    .addComponent(Button5Estrellas))
                .addGap(18, 18, 18)
                .addGroup(DialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinnerNoches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(DialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSalir2)
                    .addComponent(ButtonAceptar2)
                    .addComponent(ButtonLimpiar2))
                .addGap(39, 39, 39))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EtiquetaNombreYApellidos.setText("Nombre y Apellidos");

        CTextoNombreApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTextoNombreApellidosActionPerformed(evt);
            }
        });

        EtiquetaCiudad.setText("Ciudad");

        ComboBoxCiudades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sevilla", "Alcala", "Madrid", "Toledo" }));
        ComboBoxCiudades.setSelectedItem(null);
        ComboBoxCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCiudadesActionPerformed(evt);
            }
        });

        EtiquetaSexo.setText("Sexo");

        EtiquetaFechNacimiento.setText("Fecha de Nacimiento");

        LContraseña.setText("Contraseña");

        LRContraseña.setText("Repita Contraseña");

        buttonGroupSexo.add(ButtonHombre);
        ButtonHombre.setText("Hombre");

        buttonGroupSexo.add(ButtonMujer);
        ButtonMujer.setText("Mujer");

        SpinnerFechNacimiento.setModel(new javax.swing.SpinnerNumberModel(0, 0, 31, 1));

        ComboBoxMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio" }));
        ComboBoxMeses.setSelectedItem(null);

        passWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passWordActionPerformed(evt);
            }
        });

        CheckBoxCOndicionesDeUso.setText("  Acepto los terminos y condiciones de uso");
        CheckBoxCOndicionesDeUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxCOndicionesDeUsoActionPerformed(evt);
            }
        });

        ButtonLimpiar.setText("Limpiar");
        ButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimpiarActionPerformed(evt);
            }
        });

        ButtonAceptar.setText("Aceptar");
        ButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAceptarActionPerformed(evt);
            }
        });

        ButtonSalir.setText("Salir");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });

        Menu_Archivo.setText("Archivo");
        jMenuBar1.add(Menu_Archivo);

        Menu_Edita.setText("Editar");
        jMenuBar1.add(Menu_Edita);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CheckBoxCOndicionesDeUso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LRContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EtiquetaFechNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(EtiquetaSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EtiquetaCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EtiquetaNombreYApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CTextoNombreApellidos)
                                        .addComponent(ComboBoxCiudades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(ButtonHombre)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                            .addComponent(ButtonMujer)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SpinnerFechNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ComboBoxMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(passWord)
                                    .addComponent(rePassword))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(ButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(ButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaNombreYApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CTextoNombreApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonHombre)
                    .addComponent(ButtonMujer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaFechNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinnerFechNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LRContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CheckBoxCOndicionesDeUso)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void mensaje(String mensaje){
    JOptionPane.showMessageDialog(this, mensaje);
}
    
    private void CTextoNombreApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTextoNombreApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CTextoNombreApellidosActionPerformed

    private void ComboBoxCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCiudadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxCiudadesActionPerformed

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void CheckBoxCOndicionesDeUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxCOndicionesDeUsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxCOndicionesDeUsoActionPerformed

    private void ButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAceptarActionPerformed
        if (CheckBoxCOndicionesDeUso.isSelected()){
            //Aqui ya esta marcado el checkbox
            /* Miramos que no estan vacios los campos de password */
            if((passWord.getPassword().length>0) && (rePassword.getPassword().length>0)){
                //No estan vacias las contraseñas
                password = String.valueOf(passWord.getPassword());
                repassword = String.valueOf(rePassword.getPassword());
                
                if(password.equals(repassword)){
                   System.out.println("Estamos Aqui");
                   DialogoViaje.getContentPane().setBackground(Color.BLUE);
                   DialogoViaje.setVisible(true);
                }else{
                mensaje("Las contraseñas non coinciden");
                }                
            }else{
                mensaje("No debe de haber contraseñas vacias");               
            }
        }else{
           mensaje("No has aceptado las condiciones de uso");
        }
    }//GEN-LAST:event_ButtonAceptarActionPerformed

    private void passWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passWordActionPerformed
       
    }//GEN-LAST:event_passWordActionPerformed

    private void ButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimpiarActionPerformed
        CTextoNombreApellidos.setText("");
        ComboBoxCiudades.setSelectedItem(null);
        buttonGroupSexo.clearSelection();        
        SpinnerFechNacimiento.setValue(0);
        ComboBoxMeses.setSelectedItem(null);
        passWord.setText("");
        rePassword.setText("");
        CheckBoxCOndicionesDeUso.setSelected(false);
    }//GEN-LAST:event_ButtonLimpiarActionPerformed

    private void ButtonSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalir2ActionPerformed
        DialogoViaje.setVisible(false);
    }//GEN-LAST:event_ButtonSalir2ActionPerformed

    private void ButtonAceptar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAceptar2ActionPerformed
        String destino;
        if(ButtonCanarias.isSelected()){
            destino = "Canarias";
        }else{
            if(ButtonValencia.isSelected()){
                destino = "Valencia";
            }else{
                if(ButtonPortugal.isSelected()){
                    destino = "Portugal";
                }else{
                    destino = "";
                }
            }
        }
        if(destino.equalsIgnoreCase("")){
            mensaje("No has seleccionado destino");
        }else{
          //Aqui ya tenemos destino
        }
    }//GEN-LAST:event_ButtonAceptar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Button3Estrellas;
    private javax.swing.JRadioButton Button4Estrellas;
    private javax.swing.JRadioButton Button5Estrellas;
    private javax.swing.JButton ButtonAceptar;
    private javax.swing.JButton ButtonAceptar2;
    private javax.swing.JRadioButton ButtonCanarias;
    private javax.swing.JRadioButton ButtonHombre;
    private javax.swing.JButton ButtonLimpiar;
    private javax.swing.JButton ButtonLimpiar1;
    private javax.swing.JButton ButtonLimpiar2;
    private javax.swing.JRadioButton ButtonMujer;
    private javax.swing.JRadioButton ButtonPortugal;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JButton ButtonSalir2;
    private javax.swing.JRadioButton ButtonValencia;
    private javax.swing.JTextField CTextoNombreApellidos;
    private javax.swing.JCheckBox CheckBoxCOndicionesDeUso;
    private javax.swing.JComboBox<String> ComboBoxCiudades;
    private javax.swing.JComboBox<String> ComboBoxMeses;
    private javax.swing.JDialog DialogoViaje;
    private javax.swing.JLabel EtiquetaCiudad;
    private javax.swing.JLabel EtiquetaDestino;
    private javax.swing.JLabel EtiquetaFechNacimiento;
    private javax.swing.JLabel EtiquetaHotel;
    private javax.swing.JLabel EtiquetaNombreYApellidos;
    private javax.swing.JLabel EtiquetaSexo;
    private javax.swing.JLabel LContraseña;
    private javax.swing.JLabel LRContraseña;
    private javax.swing.JMenu Menu_Archivo;
    private javax.swing.JMenu Menu_Edita;
    private javax.swing.JSpinner SpinnerFechNacimiento;
    private javax.swing.JSpinner SpinnerNoches;
    private javax.swing.JTextArea TextArea1;
    private javax.swing.ButtonGroup buttonGroupDestino;
    private javax.swing.ButtonGroup buttonGroupHotel;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JPasswordField rePassword;
    // End of variables declaration//GEN-END:variables
}
