
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jesus
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    Viaje viaje;
    
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        viaje = new Viaje();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDeBotonesSexo = new javax.swing.ButtonGroup();
        dialogoViaje = new javax.swing.JDialog();
        etiquetaDestino = new javax.swing.JLabel();
        botonLimpiarViaje = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        radioBotonCanarias = new javax.swing.JRadioButton();
        radioBotonValencia = new javax.swing.JRadioButton();
        radioBotonPotugal = new javax.swing.JRadioButton();
        radioBoton1Estrella = new javax.swing.JRadioButton();
        radioBoton4Estrellas = new javax.swing.JRadioButton();
        radioBoton5Estrellas = new javax.swing.JRadioButton();
        etiquetaNoches = new javax.swing.JLabel();
        spinerNumeroDeNoches = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        grupoBotonDestino = new javax.swing.ButtonGroup();
        grupoBotonHotel = new javax.swing.ButtonGroup();
        etiquetaNomApell = new javax.swing.JLabel();
        CTextoNombApell = new javax.swing.JTextField();
        etiquetaCiudad = new javax.swing.JLabel();
        comboCiudad = new javax.swing.JComboBox<>();
        etiquetasSexo = new javax.swing.JLabel();
        radioBotonHombre = new javax.swing.JRadioButton();
        radioBotonMujer = new javax.swing.JRadioButton();
        etiquetaFechaDeNacimiento = new javax.swing.JLabel();
        spinnerDiaNacimiento = new javax.swing.JSpinner();
        comboMeses = new javax.swing.JComboBox<>();
        etiquetaContraseña = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        passWord = new javax.swing.JPasswordField();
        rePassword = new javax.swing.JPasswordField();
        checkBoxCondicionesUso = new javax.swing.JCheckBox();
        botonLimpiar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu1 = new javax.swing.JMenu();
        MenuEdicion = new javax.swing.JMenu();

        dialogoViaje.setBackground(new java.awt.Color(10, 10, 184));
        dialogoViaje.setSize(new java.awt.Dimension(600, 400));

        etiquetaDestino.setText("DESTINO");

        botonLimpiarViaje.setText("Limpiar");
        botonLimpiarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarViajeActionPerformed(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("HOTEL");

        grupoBotonDestino.add(radioBotonCanarias);
        radioBotonCanarias.setText("Canarias");

        grupoBotonDestino.add(radioBotonValencia);
        radioBotonValencia.setText("Valencia");

        grupoBotonDestino.add(radioBotonPotugal);
        radioBotonPotugal.setText("Portugal");

        grupoBotonHotel.add(radioBoton1Estrella);
        radioBoton1Estrella.setText("3 Estrellas - 50 €");

        grupoBotonHotel.add(radioBoton4Estrellas);
        radioBoton4Estrellas.setText("4 Estrellas - 75 €");

        grupoBotonHotel.add(radioBoton5Estrellas);
        radioBoton5Estrellas.setText("5 Estrellas - 100 €");

        etiquetaNoches.setText("DIAS");

        spinerNumeroDeNoches.setModel(new javax.swing.SpinnerNumberModel(0, 0, 365, 1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout dialogoViajeLayout = new javax.swing.GroupLayout(dialogoViaje.getContentPane());
        dialogoViaje.getContentPane().setLayout(dialogoViajeLayout);
        dialogoViajeLayout.setHorizontalGroup(
            dialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoViajeLayout.createSequentialGroup()
                .addGroup(dialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoViajeLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(etiquetaDestino)
                        .addGap(182, 182, 182)
                        .addComponent(jLabel2))
                    .addGroup(dialogoViajeLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(dialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogoViajeLayout.createSequentialGroup()
                                .addComponent(botonLimpiarViaje)
                                .addGap(121, 121, 121)
                                .addComponent(jButton1)
                                .addGap(102, 102, 102)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(radioBotonValencia)
                            .addGroup(dialogoViajeLayout.createSequentialGroup()
                                .addGroup(dialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioBotonCanarias)
                                    .addComponent(radioBotonPotugal))
                                .addGap(176, 176, 176)
                                .addGroup(dialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioBoton5Estrellas)
                                    .addComponent(radioBoton4Estrellas)
                                    .addComponent(radioBoton1Estrella)))))
                    .addGroup(dialogoViajeLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(etiquetaNoches)
                        .addGap(38, 38, 38)
                        .addComponent(spinerNumeroDeNoches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoViajeLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        dialogoViajeLayout.setVerticalGroup(
            dialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoViajeLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(dialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaDestino)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(dialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBotonCanarias)
                    .addComponent(radioBoton1Estrella))
                .addGap(18, 18, 18)
                .addGroup(dialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBotonValencia)
                    .addComponent(radioBoton4Estrellas))
                .addGap(21, 21, 21)
                .addGroup(dialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioBotonPotugal)
                    .addComponent(radioBoton5Estrellas))
                .addGap(35, 35, 35)
                .addGroup(dialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNoches)
                    .addComponent(spinerNumeroDeNoches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(dialogoViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLimpiarViaje)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(28, 28, 28))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaNomApell.setText("Nombre y Apellidos");

        etiquetaCiudad.setText("Ciudad");

        comboCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sevilla", "Alcalá", "Madrid", "Polonia" }));
        comboCiudad.setSelectedItem(null);

        etiquetasSexo.setText("Sexo");

        grupoDeBotonesSexo.add(radioBotonHombre);
        radioBotonHombre.setText("Hombre");

        grupoDeBotonesSexo.add(radioBotonMujer);
        radioBotonMujer.setText("Mujer");

        etiquetaFechaDeNacimiento.setText("Fecha de Nacimiento:");

        spinnerDiaNacimiento.setModel(new javax.swing.SpinnerNumberModel(0, 0, 31, 1));

        comboMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        comboMeses.setSelectedItem(null);
        comboMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMesesActionPerformed(evt);
            }
        });

        etiquetaContraseña.setText("Contraseña");

        jLabel1.setText("Repita Contraseña");

        passWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passWordActionPerformed(evt);
            }
        });

        checkBoxCondicionesUso.setText("Acepto los terminos y condiciones de uso.");

        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        Menu1.setText("Archivo");
        jMenuBar1.add(Menu1);

        MenuEdicion.setText("Edicion");
        jMenuBar1.add(MenuEdicion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkBoxCondicionesUso, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaNomApell)
                                    .addComponent(etiquetaCiudad)
                                    .addComponent(etiquetasSexo)
                                    .addComponent(etiquetaFechaDeNacimiento)
                                    .addComponent(etiquetaContraseña)
                                    .addComponent(jLabel1))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spinnerDiaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(comboMeses, 0, 286, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioBotonHombre)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioBotonMujer))
                                    .addComponent(CTextoNombApell)
                                    .addComponent(comboCiudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passWord)
                                    .addComponent(rePassword)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(botonLimpiar)
                        .addGap(151, 151, 151)
                        .addComponent(botonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNomApell)
                    .addComponent(CTextoNombApell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCiudad)
                    .addComponent(comboCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetasSexo)
                    .addComponent(radioBotonHombre)
                    .addComponent(radioBotonMujer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaFechaDeNacimiento)
                    .addComponent(spinnerDiaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaContraseña)
                    .addComponent(passWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(checkBoxCondicionesUso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLimpiar)
                    .addComponent(botonAceptar)
                    .addComponent(botonSalir))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    private void comboMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMesesActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        String password, repassword;
        if (checkBoxCondicionesUso.isSelected()){
            // Aqui ya esta marcado el check box
            //miremos que no esten vacios los campos de password
            if((passWord.getPassword().length>0) && (rePassword.getPassword().length>0)){
                //No están vacias las contraseñas
                password = String.valueOf(passWord.getPassword());
                repassword = String.valueOf(rePassword.getPassword());
                if (password.equals(repassword)){
                    //Abriremos la proxima ventana
                    dialogoViaje.getContentPane().setBackground(Color.blue);
                    dialogoViaje.setVisible(true);
                } else{
                    mensaje("Las contraseñas no coinciden");
                }
            } else{
                mensaje("No debe haber contraseñas vacias");
            }
        } else{
            mensaje("No has aceptado las condiciones de uso");
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void passWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passWordActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        CTextoNombApell.setText("");
        comboCiudad.setSelectedItem(null);
        grupoDeBotonesSexo.clearSelection();
        spinnerDiaNacimiento.setValue(0);
        comboMeses.setSelectedItem(null);
        passWord.setText("");
        rePassword.setText("");
        checkBoxCondicionesUso.setSelected(false);
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dialogoViaje.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botonLimpiarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLimpiarViajeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String destino;
        if (radioBotonCanarias.isSelected()){
            destino = "Canarias";
        } else{
            if (radioBotonValencia.isSelected()){
                destino = "Valencia";
            } else{
                if  (radioBotonPotugal.isSelected()) {
                    destino = "Portugal";
                } else {
                    destino ="";
                }
                    
            }
        }
        if (destino.equalsIgnoreCase("")){
            mensaje("No has seleccionado destino");
        }
        else{
            //Aqui ya tenemos destino... ahora veremos hotel
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CTextoNombApell;
    private javax.swing.JMenu Menu1;
    private javax.swing.JMenu MenuEdicion;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonLimpiarViaje;
    private javax.swing.JButton botonSalir;
    private javax.swing.JCheckBox checkBoxCondicionesUso;
    private javax.swing.JComboBox<String> comboCiudad;
    private javax.swing.JComboBox<String> comboMeses;
    private javax.swing.JDialog dialogoViaje;
    private javax.swing.JLabel etiquetaCiudad;
    private javax.swing.JLabel etiquetaContraseña;
    private javax.swing.JLabel etiquetaDestino;
    private javax.swing.JLabel etiquetaFechaDeNacimiento;
    private javax.swing.JLabel etiquetaNoches;
    private javax.swing.JLabel etiquetaNomApell;
    private javax.swing.JLabel etiquetasSexo;
    private javax.swing.ButtonGroup grupoBotonDestino;
    private javax.swing.ButtonGroup grupoBotonHotel;
    private javax.swing.ButtonGroup grupoDeBotonesSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JRadioButton radioBoton1Estrella;
    private javax.swing.JRadioButton radioBoton4Estrellas;
    private javax.swing.JRadioButton radioBoton5Estrellas;
    private javax.swing.JRadioButton radioBotonCanarias;
    private javax.swing.JRadioButton radioBotonHombre;
    private javax.swing.JRadioButton radioBotonMujer;
    private javax.swing.JRadioButton radioBotonPotugal;
    private javax.swing.JRadioButton radioBotonValencia;
    private javax.swing.JPasswordField rePassword;
    private javax.swing.JSpinner spinerNumeroDeNoches;
    private javax.swing.JSpinner spinnerDiaNacimiento;
    // End of variables declaration//GEN-END:variables
}
